### ISSUE TITLE
Package name in README.md differs from package name at packagist

### ISSUE THREAD

**Issue by nahooda** [Flowpack/Flowpack.StructuredEditing#4]
Since the package name in README.md differs from the package name at packagist.org, installation throws an error "Could not find package flowpack/structured-editing@dev at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability".

Doesn't work: composer require flowpack/structured-editing (README.md)
Works: composer require flowpack/structuredediting (packagist.org)

**Comment by dimaip** [comment]
Thanks!
